import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, '../..');
const args = process.argv.slice(2);
const env = { ...process.env };

configureLinuxTrayPkgConfig(env);

const tauriCli = join(
  projectRoot,
  'node_modules',
  '@tauri-apps',
  'cli',
  'tauri.js'
);
const child = spawn(process.execPath, [tauriCli, ...args], {
  cwd: projectRoot,
  env,
  stdio: 'inherit'
});

child.on('exit', (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
  } else {
    process.exit(code ?? 1);
  }
});

child.on('error', (error) => {
  console.error(`[tauri-wrapper] failed to start Tauri CLI: ${error.message}`);
  process.exit(1);
});

function configureLinuxTrayPkgConfig(env) {
  if (process.platform !== 'linux') {
    return;
  }

  const variants = [
    {
      envValue: '1',
      pcName: 'ayatana-appindicator3-0.1',
      libraryName: 'libayatana-appindicator3.so.1',
      linkerName: 'ayatana-appindicator3',
      displayName: 'Ayatana AppIndicator'
    },
    {
      envValue: '0',
      pcName: 'appindicator3-0.1',
      libraryName: 'libappindicator3.so.1',
      linkerName: 'appindicator3',
      displayName: 'AppIndicator'
    }
  ];

  const forced = env.TAURI_LINUX_AYATANA_APPINDICATOR;
  const candidates =
    forced == null
      ? variants
      : variants.filter((variant) =>
          forced === 'true' || forced === '1'
            ? variant.envValue === '1'
            : variant.envValue === '0'
        );

  if (candidates.some((variant) => pkgConfigExists(variant.pcName, env))) {
    return;
  }

  for (const variant of candidates) {
    const libraryPath = findLibrary(variant.libraryName);
    if (!libraryPath) {
      continue;
    }

    const pkgConfigDir = join(projectRoot, 'src-tauri', '.pkgconfig');
    mkdirSync(pkgConfigDir, { recursive: true });
    writePkgConfig(pkgConfigDir, variant, dirname(libraryPath));

    env.PKG_CONFIG_PATH = prependPath(pkgConfigDir, env.PKG_CONFIG_PATH);
    env.TAURI_LINUX_AYATANA_APPINDICATOR = variant.envValue;
    return;
  }
}

function pkgConfigExists(name, env) {
  const result = spawnSync('pkg-config', ['--exists', name], {
    env,
    stdio: 'ignore'
  });
  return result.status === 0;
}

function findLibrary(libraryName) {
  const commonDirs = [
    '/usr/lib64',
    '/usr/lib',
    '/usr/local/lib64',
    '/usr/local/lib',
    '/lib64',
    '/lib',
    '/usr/lib/x86_64-linux-gnu',
    '/lib/x86_64-linux-gnu',
    '/usr/lib/aarch64-linux-gnu',
    '/lib/aarch64-linux-gnu'
  ];

  for (const dir of commonDirs) {
    const candidate = join(dir, libraryName);
    if (existsSync(candidate)) {
      return candidate;
    }
  }

  const ldconfig = spawnSync('ldconfig', ['-p'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore']
  });
  if (ldconfig.status !== 0 || !ldconfig.stdout) {
    return null;
  }

  for (const line of ldconfig.stdout.split('\n')) {
    if (!line.includes(libraryName)) {
      continue;
    }
    const match = line.match(/=>\s*(.+)$/);
    if (match?.[1] && existsSync(match[1])) {
      return match[1];
    }
  }

  return null;
}

function writePkgConfig(pkgConfigDir, variant, libdir) {
  const pcPath = join(pkgConfigDir, `${variant.pcName}.pc`);
  const contents = `# AUTO-GENERATED by src-tauri/scripts/tauri.mjs - do not edit.
libdir=${libdir}

Name: ${variant.displayName}
Description: Local pkg-config shim for Tauri Linux tray bundling
Version: 0.1
Libs: -L\${libdir} -l${variant.linkerName}
Cflags:
`;
  writeFileSync(pcPath, contents);
}

function prependPath(entry, existing) {
  return existing ? `${entry}:${existing}` : entry;
}
